name: build java application
on:
 push:
  branches:
   - master
jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v5
      - name: Install nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          ##distribution: 'temurin'
          cache: 'npm'
      - name: install the dependencies
        run: npm ci
      - name: RUn tests
        run: npm test
      - name: build code
        run: npm run build
      - name: upload the file to github
        uses: actions/upload-artifact@v4
        with:
         name: my-file
         path: /home/runner/work/Nodejs-GithubActions/Nodejs-GithubActions/test.json        
